config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('well.urls', namespace='курс')),
    path('users/', include('users.urls', namespace='users')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, UserListView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('user/list', UserListView.as_view(), name='users-list')
]

well/urls.py
from django.urls import path

from well.apps import WellConfig
from well.views import index, contacts, WellListView, WellDeleteView, WellUpdateView, WellCreateView, WellDetailView, \
    LessonListView, LessonCreateView, LessonUpdateView, LessonDeleteView, LessonDetailView

app_name = WellConfig.name

urlpatterns = [
    path('', index, name='home'),
    path('contacts/', contacts, name='contacts'),
    path('well/list', WellListView.as_view(), name='well-list'),
    path('well/create', WellCreateView.as_view(), name='well-create'),
    path('well/update/<int:pk>', WellUpdateView.as_view(), name='well-update'),
    path('well/delete/<int:pk>', WellDeleteView.as_view(), name='well-delete'),
    path('well/<int:pk>', WellDetailView.as_view(), name='well-view'),

    path('lesson/list', LessonListView.as_view(), name='lesson-list'),
    path('lesson/create', LessonCreateView.as_view(), name='lesson-create'),
    path('lesson/update/<int:pk>', LessonUpdateView.as_view(), name='lesson-update'),
    path('lesson/delete/<int:pk>', LessonDeleteView.as_view(), name='lesson-delete'),
    path('lesson/<int:pk>', LessonDetailView.as_view(), name='lesson-view'),
]

well/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Well(models.Model):
    title = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(verbose_name='описание', **NULLABLE)
    preview = models.ImageField(upload_to='well/', verbose_name='превью', **NULLABLE)
    documentation = models.URLField(max_length=200, verbose_name='ссылка на документацию')

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'курс'
        verbose_name_plural = 'курсы'


class Lesson(models.Model):
    title = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(verbose_name='описание', **NULLABLE)
    preview = models.ImageField(upload_to='lesson/', verbose_name='превью', **NULLABLE)
    video_url = models.URLField(verbose_name='ссылка на видео', **NULLABLE)
    well = models.ForeignKey(Well, on_delete=models.CASCADE, verbose_name='курс', **NULLABLE,
                             related_name='lessons')

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'урок'
        verbose_name_plural = 'уроки'

well/forms.py
from django import forms

from well.models import Well, Lesson


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class WellForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Well
        fields = "__all__"


class LessonForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Lesson
        fields = '__all__'

well/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from well.forms import WellForm, LessonForm
from well.models import Well, Lesson


def index(request):
    return render(request, 'well/home.html')


@login_required
def contacts(request):
    return render(request, 'well/contacts.html')


class WellListView(LoginRequiredMixin, ListView):
    model = Well
    template_name = "well/well_list.html"


class WellCreateView(LoginRequiredMixin, CreateView):
    model = Well
    form_class = WellForm
    success_url = reverse_lazy("well:well-list")


class WellUpdateView(LoginRequiredMixin, UpdateView):
    model = Well
    form_class = WellForm
    success_url = reverse_lazy("well:well-list")


class WellDeleteView(LoginRequiredMixin, DeleteView):
    model = Well
    success_url = reverse_lazy("well:well-list")
    template_name = "well/well_confirm_delete.html"


class WellDetailView(LoginRequiredMixin, DeleteView):
    model = Well
    template_name = "well/well_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        well = get_object_or_404(Well, pk=self.kwargs['pk'])
        lessons = well.lessons.all()
        context['lessons'] = lessons
        return context


class LessonListView(LoginRequiredMixin, ListView):
    model = Lesson
    template_name = "well/lesson_list.html"


class LessonCreateView(LoginRequiredMixin, CreateView):
    model = Lesson
    form_class = LessonForm
    success_url = reverse_lazy("well:lesson-list")


class LessonUpdateView(LoginRequiredMixin, UpdateView):
    model = Lesson
    form_class = LessonForm
    success_url = reverse_lazy("well:lesson-list")


class LessonDeleteView(LoginRequiredMixin, DeleteView):
    model = Lesson
    success_url = reverse_lazy("well:lesson-list")
    template_name = "well/well_confirm_delete.html"


class LessonDetailView(LoginRequiredMixin, DeleteView):
    model = Lesson
    template_name = "well/lesson_detail.html"

well/templates/well/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">The Art of Learning</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'well:home' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'well:well-list' %}">Курсы</a>
        {#        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>#}
        {% if user.is_staff or user.is_superuser %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'well:lesson-list' %}">Уроки</a>
        {% endif %}
        {#        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:messages_list' %}">Сообщения</a>#}
        <a class="p-2 btn btn-outline-primary" href="{% url 'well:contacts' %}">Контакты</a>
    </nav>
    <nav class="ms-md-auto">
        {% if user.is_authenticated %}
            {% if user.is_staff %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:users-list' %}">Список пользователей</a>
            {% endif %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
        {% endif %}
    </nav>
</div>

<div class="container mt-4">

    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                The Art of Learning
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted">+79834223423</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'well:home' %}">Главная</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

well/templates/well/contacts.html
{% extends 'well/base.html' %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Контакты</h1>
    </div>
    <div class="container">
        <div class="row text-start">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr class="table-info">
                                <td class="w-25">Страна</td>
                                <td>Россия</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>12-5124341</td>
                            </tr>
                            <tr class="table-info">
                                <td class="w-25">Адрес</td>
                                <td>г. Москва, ул. Дорожная 12</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                       required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Сообщите о проблеме" required></textarea>
                            </div>
                            <button type="submit" class="btn  btn-lg btn-info btn-outline-light">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

well/templates/well/home.html
{% extends 'well/base.html' %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Сервис рассылок</h1>
    </div>
    <div>
        <p class="fs-4">3 случайные статьи из блога:</p>
        <p>
            <button class="p-2 btn btn-outline-success" type="button" data-bs-toggle="collapse"
                    data-bs-target="#bye" aria-expanded="false"
                    aria-controls="bye">
                Статьй
            </button>
        </p>

{#        {% for object in random_articles %}#}
{#            <div class="collapse mb-2" id="bye">#}
{#                <div class="card card-body">#}
{#                    <li><a class="text-muted" href="{% url 'blog:view' object.pk %}">{{ object.header }}</a></li>#}
{#                    {{ object.content|truncatechars:50 }}#}
{#                </div>#}
{#            </div>#}
{#        {% endfor %}#}
        <div class="col-12">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4>Статистика рассылок</h4>
                    </div>
{#                    <div class="card-body">#}
{#                        <p>Всего рассылок: {{ total_mailings }}</p>#}
{#                        <p>Активных рассылок: {{ active_mailings }}</p>#}
{#                        <p>Уникальных клиентов для рассылок: {{ unique_clients }}</p>#}
{#                    </div>#}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

well/templates/well/lesson_confirm_delete.html
{% extends 'well/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Удаление урока</h1>
    </div>
    <div class="col-12"></div>
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите ли удалить урок? {{ object.title}} ?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'well:lesson-list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

well/templates/well/lesson_detail.html
{% extends 'well/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Информация о курсе</h1>
    </div>
    <div class="col-12">
        <div class="row">

            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Тема: {{ object.title }}
                        </h3>
                    </div>
                    <div class="card-body">
                        <p>
                            Описание: {{ object.description }}
                        </p>
                        <p>
                            Документация: {{ object.documentation }}
                        </p>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

well/templates/well/lesson_form.html
{% extends 'well/base.html' %}

{% block content %}
    {% if object %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Редактирование урока</h1>
        </div>
    {% else %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Создание урока</h1>
        </div>
    {% endif %}
    <div class="col-12"></div>
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Изменить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

well/templates/well/lesson_list.html
{% extends 'well/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Список уроков</h1>
    </div>
    <div class="row text-center">
        <div class="col-12">
            <div class="col-12">
                {% if user.is_staff or user.is_superuser %}
                    <a class='btn btn-primary' href="{% url 'well:lesson-create' %}">Добавить урок</a>
                {% endif %}
            </div>
        </div>
        {% for object in object_list %}
            <div class="p-3 col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ object.documentation|truncatechars:30 }}</li>
                        </ul>
                        <div class="btn-group ml-4">
                            {% if user.is_staff or user.is_superuser %}
                                <a class="p-2 btn btn-outline-primary"
                                   href="{% url 'well:lesson-update' object.pk %}">Изменение</a>
                            {% endif %}
                            <a class="p-2 btn btn-outline-danger"
                               href="{% url 'well:lesson-view' object.pk %}">Просмотр</a>
                            {% if user.is_staff or user.is_superuser %}
                                <a class="p-2 btn btn-outline-danger"
                                   href="{% url 'well:lesson-delete' object.pk %}">Удаление</a>
                            {% endif %}
                        </div>
                        <div class="btn-group ml-4">
                            {#                            {% if not user.is_staff or user.is_superuser %}#}
                            {#                                <a class="p-2 btn btn-outline-success mt-2"#}
                            {#                                   href="{% url 'mailing:mailing_clients' object.pk %}">Клиенты</a>#}
                            {#                            {% endif %}#}
                            {#                            {% if user.is_staff%}#}
                            {#                                {% if object.status == object.STARTED %}#}
                            {#                                    <a class="p-2 btn btn-outline-success mt-2"#}
                            {#                                       href="{% url 'mailing:stop_mailing' object.pk %}">Остановить рассылку</a>#}
                            {#                                {% else %}#}
                            {#                                    <a class="p-2 btn btn-outline-success mt-2"#}
                            {#                                       href="{% url 'mailing:stop_mailing' object.pk %}">Запустить рассылку</a>#}
                            {#                                {% endif %}#}
                            {#                            {% endif %}#}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

well/templates/well/well_confirm_delete.html
{% extends 'well/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Удаление курса</h1>
    </div>
    <div class="col-12"></div>
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите ли удалить курс? {{ object.title}} ?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'well:well-list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

well/templates/well/well_detail.html
{% extends 'well/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Информация о курсе</h1>
    </div>
    <div class="col-12">
        <div class="row">

            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Тема: {{ object.title }}
                        </h3>
                    </div>
                    <div class="card-body">
                        <p>
                            Описание: {{ object.description }}
                        </p>
                        <p>
                            Документация: {{ object.documentation }}
                        </p>
                    </div>
                    <div class="card-footer">
                        {% if lessons %}
                            <h6>Уроки:</h6>
                            <ul>
                                {% for lesson in lessons %}
                                    <li>
                                        <a href="{% url 'well:lesson-view' pk=lesson.pk %}">
                                            {{ lesson.title }}
                                        </a> - {{ lesson.description }}
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p>Уроки для данного курса отсутствуют.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

well/templates/well/well_form.html
{% extends 'well/base.html' %}

{% block content %}
    {% if object %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Редактирование курса</h1>
        </div>
    {% else %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Создание курса</h1>
        </div>
    {% endif %}
    <div class="col-12"></div>
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Отправить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

well/templates/well/well_list.html
{% extends 'well/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Сервис рассылок</h1>
    </div>
    <div class="row text-center">
        <div class="col-12">
            <div class="col-12">
                {% if user.is_staff or user.is_superuser %}
                    <a class='btn btn-primary' href="{% url 'well:well-create' %}">Добавить курс</a>
                {% endif %}
            </div>
        </div>
        {% for object in object_list %}
            <div class="p-3 col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ object.documentation|truncatechars:30 }}</li>
                        </ul>
                        <div class="btn-group ml-4">
                            {% if user.is_staff or user.is_superuser %}
                                <a class="p-2 btn btn-outline-primary"
                                   href="{% url 'well:well-update' object.pk %}">Изменение</a>
                            {% endif %}
                            <a class="p-2 btn btn-outline-danger"
                               href="{% url 'well:well-view' object.pk %}">Просмотр</a>
                            {% if user.is_staff or user.is_superuser %}
                                <a class="p-2 btn btn-outline-danger"
                                   href="{% url 'well:well-delete' object.pk %}">Удаление</a>
                            {% endif %}
                        </div>
                        <div class="btn-group ml-4">
                            {#                            {% if not user.is_staff or user.is_superuser %}#}
                            {#                                <a class="p-2 btn btn-outline-success mt-2"#}
                            {#                                   href="{% url 'mailing:mailing_clients' object.pk %}">Клиенты</a>#}
                            {#                            {% endif %}#}
                            {#                            {% if user.is_staff%}#}
                            {#                                {% if object.status == object.STARTED %}#}
                            {#                                    <a class="p-2 btn btn-outline-success mt-2"#}
                            {#                                       href="{% url 'mailing:stop_mailing' object.pk %}">Остановить рассылку</a>#}
                            {#                                {% else %}#}
                            {#                                    <a class="p-2 btn btn-outline-success mt-2"#}
                            {#                                       href="{% url 'mailing:stop_mailing' object.pk %}">Запустить рассылку</a>#}
                            {#                                {% endif %}#}
                            {#                            {% endif %}#}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}